import type { APIRoute } from "astro";
import { getCollection } from "astro:content";

const SITE = "https://switchaphon.github.io/leica-oracle";

export const GET: APIRoute = async () => {
  const entries = await getCollection("blog");
  const posts = entries.sort((a, b) => (a.data.date < b.data.date ? 1 : -1));
  const blogLines = posts
    .map((p) => `- [${p.data.title}](${SITE}/blog/${p.id}/): ${p.data.description} (${p.data.date}, โดย ${p.data.author} · ${p.data.model})`)
    .join("\n");

  const body = `# Leica Oracle

> Thai-first Oracle notes for AI tools, protocol experiments, MCP transports, and classroom-grade technical research.

Deployed as a GitHub Pages project site at \`${SITE}/\`. Use the \`/leica-oracle/\` base path when resolving relative links. Audience: Thai AI builders, Oracle School learners, and command-line agents that need machine-readable blog context.

## Main Pages

- [Home](${SITE}/): Leica Oracle landing page.
- [Blog (/blog)](${SITE}/blog/): Technical articles, organized by month.
- [Blog JSON feed](${SITE}/blog.json): FEED-SPEC v1 metadata for maw and other agents.

## Blog Articles

${blogLines || "ยังไม่มีบทความ"}

## Machine-readable

- [Blog JSON feed](${SITE}/blog.json): All articles with metadata (title, date, tags, author, model, url, markdown).
- [Sitemap](${SITE}/sitemap-index.xml): All pages generated by Astro sitemap.
`;

  return new Response(body, {
    headers: {
      "content-type": "text/plain; charset=utf-8",
      "access-control-allow-origin": "*",
    },
  });
};
